<a href="https://colab.research.google.com/github/koztigrkentavr/kalkulyator/blob/main/mohirdev_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [1]:
import numpy as np

In [3]:
np.__version__

'2.0.2'

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [4]:
arr = np.array([1,2,4,6,7])
arr

array([1, 2, 4, 6, 7])

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



In [5]:
arr = np.zeros(9)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

`💡Ishora` np.zeros

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [8]:
array = np.zeros(11)
memory_size = array.nbytes
memory_size

88

In [10]:
print(array.size)

11


#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [11]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [12]:
arr = np.zeros(12)
arr[5] = 1
arr

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [13]:
vector = np.arange(20,60)
vector

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [14]:
vector = np.arange(1,11)
vec_tes = vector[::-1]
vec_tes

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [16]:
arr = np.arange(12,21)
mat = arr.reshape(3,3)
mat


array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [17]:
matrix = np.array([3,7,0,0,9,0])
nonzero_ind = np.nonzero(matrix)
nonzero_ind

(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [18]:
arr = np.random.random((2,2,2))
arr

array([[[0.9787031 , 0.19559006],
        [0.73955776, 0.57177846]],

       [[0.34631335, 0.67284989],
        [0.5889502 , 0.52248567]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [19]:
arr = np.random.random((9,9))
max_qiy = arr.max()
min_qiy = arr.min()
max_qiy,min_qiy

(np.float64(0.9843090631571271), np.float64(0.015024733027770854))

#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [20]:
0*np.nan

nan

In [21]:
np.nan == np.nan

False

In [22]:
np.inf > np.inf

False

In [23]:
np.nan - np.nan

nan

In [24]:
np.nan in set([np.nan])

True

In [25]:
0.7 == 7*0.1

False

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [26]:
A = np.ones((6,3))
B = np.ones((3,4))
C = np.dot(A,B)
print(C)

[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [27]:
print(sum(range(5),-1))

9


In [28]:
from numpy import*
print(sum(range(5),-1))

10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [29]:
a = np.array([1,2])
b = np.array([4,5])
a > b

array([False, False])

In [30]:
a >= b

array([False, False])

In [31]:
a < b

array([ True,  True])

In [32]:
a <= b

array([ True,  True])

#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [33]:
np.array(0) / np.array(0)

<ipython-input-33-3585dcb7ab9b>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


np.float64(nan)

In [34]:
np.array(0) // np.array(0)

<ipython-input-34-4764261090d0>:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


np.int64(0)

In [35]:
np.array([np.nan]).astype(int).astype(float)

<ipython-input-35-ea171f4782f5>:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [36]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
um_qiy = np.intersect1d(a,b)
print(um_qiy)

[4 5]


#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [37]:
a = np.random.uniform(0,10,5)
print("Asl massiv:", a)

Asl massiv: [1.47724039 4.81907936 1.08472488 3.47885003 9.36680509]


In [38]:
but_qis = a - (a%1)
print(but_qis)

[1. 4. 1. 3. 9.]


In [39]:
#2-usul
but_qis = np.floor(a)
print(but_qis)

[1. 4. 1. 3. 9.]


In [40]:
but_qis = a.astype(int)
print(but_qis)

[1 4 1 3 9]


In [41]:
but_qis = np.trunc(a)
print(but_qis)

[1. 4. 1. 3. 9.]


#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [42]:
mat = np.arange(3).repeat(3).reshape(3,3)
print(mat)

[[0 0 0]
 [1 1 1]
 [2 2 2]]


#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [43]:
vector = np.random.rand(10)
print(vector)

[0.4434467  0.89654598 0.39535655 0.39278907 0.79638091 0.38637022
 0.84652934 0.34342974 0.49143114 0.3307826 ]


In [45]:
vec_sar = np.sort(vector)
print(vec_sar)

[0.3307826  0.34342974 0.38637022 0.39278907 0.39535655 0.4434467
 0.49143114 0.79638091 0.84652934 0.89654598]


#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [46]:
A = np.random.rand(3,3)
B = np.random.rand(3,3)
print(A)
print(B)

[[0.79641525 0.38685861 0.79212582]
 [0.35684622 0.86772889 0.48405405]
 [0.70902292 0.38700314 0.36808053]]
[[0.29087502 0.79006641 0.64513626]
 [0.79511762 0.7365543  0.04264375]
 [0.48033116 0.75541536 0.42681303]]


In [47]:
print(np.array_equal(A,B))

False


In [48]:
print(np.allclose(A,B))

False


#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [51]:
A = np.ones((6,3))
B = np.ones((3,4))
C = np.dot(A,B)
print(C)


[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [52]:
vec = np.random.rand(5)
print(vec)

[0.24471044 0.78115651 0.36736268 0.52182841 0.94372406]


In [53]:
max_index = np.argmax(vec)
vec[max_index] = 0
print(vec)

[0.24471044 0.78115651 0.36736268 0.52182841 0.        ]


#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [54]:
import numpy as np

In [58]:
bugun = np.datetime64('today')
bugun

np.datetime64('2025-05-15')

In [59]:
kecha = today - np.timedelta64(1,'D')
erta = today + np.timedelta64(1,'D')
print(bugun,kecha,erta)

2025-05-15 2025-05-14 2025-05-16


#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [62]:
dates = np.arange('2016-01', '2016-02', dtype = 'datetime64[D]')
print(dates)


['2016-01-01' '2016-01-02' '2016-01-03' '2016-01-04' '2016-01-05'
 '2016-01-06' '2016-01-07' '2016-01-08' '2016-01-09' '2016-01-10'
 '2016-01-11' '2016-01-12' '2016-01-13' '2016-01-14' '2016-01-15'
 '2016-01-16' '2016-01-17' '2016-01-18' '2016-01-19' '2016-01-20'
 '2016-01-21' '2016-01-22' '2016-01-23' '2016-01-24' '2016-01-25'
 '2016-01-26' '2016-01-27' '2016-01-28' '2016-01-29' '2016-01-30'
 '2016-01-31']


#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [63]:
arr = np.random.random(10)*10
print(arr)

[2.49126355 8.89563822 3.78842414 2.81148574 1.25981546 0.7428108
 9.87335789 2.09541059 4.18674641 5.83440909]


In [70]:
but_qism = arr//1
print(but_qism)

[2. 8. 3. 2. 1. 0. 9. 2. 4. 5.]


In [71]:
but_qism = np.floor(arr)
print(but_qism)

[2. 8. 3. 2. 1. 0. 9. 2. 4. 5.]


In [72]:
but_qism = arr.astype(int)
print(but_qism)


[2 8 3 2 1 0 9 2 4 5]


In [73]:
but_qism = np.trunc(arr)
print(but_qism)

[2. 8. 3. 2. 1. 0. 9. 2. 4. 5.]


#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [77]:
array = np.random.random(1000000)
sum_np_sum = np.sum(array)
print(sum_np_sum)

500084.0347986135


In [78]:
sum2 = np.add.reduce(array)
print(sum2)

500084.0347986135


In [79]:
import time

In [80]:
start_time = time.time()
np.sum(array)
print(f"np.sum uchun vaqt: {time.time()- start_time:.10f} soniya")

np.sum uchun vaqt: 0.0031955242 soniya


In [81]:
# np.add.reduce uchun
start_time = time.time()
np.add.reduce(array)
print(f"np.add.reduce uchun vaqt:{time.time()-start_time:.10f} soniya")

np.add.reduce uchun vaqt:0.0030419827 soniya


#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [83]:
array = np.array([1,2,3,4,5])
arr2 = np.zeros(array.size*4 - 3, dtype=int)
arr2[::4] = array
print(arr2)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [84]:
import numpy as np
from numpy.lib import stride_tricks

In [87]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])

In [88]:
b = stride_tricks.as_strided(a,shape=(11,4),strides=(a.itemsize,a.itemsize))
print(b)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [90]:
a = np.array([1,2,3,4,5,6,7,3,4,8,9,1])
unique,counts = np.unique(a,return_counts=True)
uxsh_qiy = unique[counts > 1]
print(uxsh_qiy)

[1 3 4]


#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`

32.Data Sciens tist Python tilini va uning qaysi kutubxonalarini bilishi kerak?

Javob: U Python tilini yaxshi bilishi, uning numpy, pandas, matplotlib, seaborn, scikit-learn, tensorflow, pytorch kabi kutubxonalarini shuningdek, chiziqli algebra, statistikani bilishiki kerak.