<a href="https://colab.research.google.com/github/koztigrkentavr/kalkulyator/blob/main/NumpyAssign_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ![Imgur](https://i.imgur.com/5pXzCIu.png)

# **DATA SCIENCE VA SUN'IY INTELLEKT PRAKTIKUM**

## Ma'lumotlar tahlili. Numpy kutubxonasi.

# **2-AMALIY VAZIFA**

## N-o'lchamli massivlarga ishov berish

In [ ]:
# Numpy kutubxonasini chaqirib olish
import numpy as np

### Masala(1): 2-o'lchamli massiv yaratish

**Masala sharti :** Elementlari 0 dan 9 gacha (9 ning o'zi massiv elementiga kirmaydi), qadami esa 1 ga teng bo'lgan (3, 3) o'lchamli massiv yaratuvchi funksiyani davom ettiring.  

**Yordam :**  `arange`dan foydalanish ishni osonlashtiradi


In [36]:
def nd_array():
  return np.arange(9).reshape(3,3)
print(nd_array())

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Yuqoridagi yozgan funksiyangizni tekshirish uchun, quyidagi cellni yuriting.

___

###  Masala(2): Indeks yordamida 2-o'lchamli massivlardan elementlarni  kesib olish
**Masala :** Yuqorida yaratilgan massivning elementlari 6 va 7 ga teng bo'lgan qismini kesib olish funksiyasini davom ettiring.

**Yordam :** 6 va 7 turgan indekslarni aniqlab olib, shu indekslar yordamida kesib oling. **Natija:** array([6, 7]) ko'rinishida bo'lishi kerak.

In [10]:
import numpy as np
def nd_array():
    return np.arange(9).reshape(3,3)


def sliced_array_2d():
    array = nd_array()
    return array.flatten()[6:8]
print(nd_array())
print(sliced_array_2d())

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[6 7]


### Yuqoridagi yozgan funksiyangizni tekshirish uchun, quyidagi cellni yuriting.

___

###  Masala(3): Indeks yordamida 3-o'lchamli massivdan elementlarni kesib olish

**Masala :**  3-o'lchamli massivni quyidagi listdan yarating, hamda 12, 13, 15, va 16  elementlarini kesib oluvchi funksiyani davom ettiring.  

                  [[[ 0,  1,  2],
                    [ 3,  4,  5],
                    [ 6,  7,  8]],

                   [[ 9, 10, 11],
                    [12, 13, 14],
                    [15, 16, 17]],

                   [[18, 19, 20],
                    [21, 22, 23],
                    [24, 25, 26]]]

**Yordam :** Avval massivni ikki o'lchamli massivga keltirib, keyin kesib olishni amalga oshiring.


**Natija:**  

             array([[12, 13],
                    [15, 16]])
ko'rinishida bo'lishi kerak.

In [26]:
import numpy as np
arr = np.array([
      [[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]],
      [[9,10,11],
       [12,13,14],
       [15,16,17]],
      [[18,19,20],
       [21,22,23],
       [24,25,26]]
])
def sliced_array_3d():
  return arr[1, 1:3,0:2]
print(sliced_array_3d())


[[12 13]
 [15 16]]


___

###  Masala(4): Boolean indeks yordamida 2-o'lchamli massivlardan elementlarni  kesib olish

**Masala :** Bizlarda,  
        
        ['Hasan', 'Husan', 'Javohir', 'Elyor', 'Hasan', 'Javohir', 'Elyor']

**list**dagi kishilar va ularning **ma'lumot**lari
       
      [[5, 6, 1, 1],
       [9, 1, 1, 1],
       [7, 7, 4, 2],
       [1, 5, 1, 9],
       [9, 9, 4, 5],
       [7, 5, 9, 6],
       [5, 3, 7, 4]]
ko'rinishda keltirilgan.


Mana shu ma'lumotlardan **Javohir** va **Elyor** ismlariga tegishli ma'lumotlarni Boolean indekslash yordamida kesib olish funksiyasini davom ettiring.
**Yordam :** Boolean indekslash video darsligiga murojat qiling.
**Natija:** Natija (4, 4) o'lchamli massiv ko'rinishida, hamda dastlabki ikkita qattori quyidagicha

    array([[7, 7, 4, 2],
           [1, 5, 1, 9],
           ...
           ...        ]])

In [33]:
import numpy as np
def boolean_slicing():
  names = np.array(['Hasan', 'Husan', 'Javohir', 'Elyor', 'Hasan','Javohir', 'Elyor'])
  data = np.array([[5,6,1,1],
                   [9,1,1,1],
                   [7,7,4,2],
                   [1,5,1,9],
                   [9,9,4,5],
                   [7,5,9,6],
                   [5,3,7,4]])
  mask = (names == 'Javohir')| (names == 'Elyor')
  return data[mask]
print(boolean_slicing())


[[7 7 4 2]
 [1 5 1 9]
 [7 5 9 6]
 [5 3 7 4]]


### Yuqoridagi yozgan funksiyangizni tekshirish uchun, quyidagi cellni yuriting.