<a href="https://colab.research.google.com/github/koztigrkentavr/kalkulyator/blob/main/NumpyAssign_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ![Imgur](https://i.imgur.com/5pXzCIu.png)

# **DATA SCIENCE VA SUN'IY INTELLEKT PRAKTIKUM**

## Ma'lumotlar tahlili. Numpy kutubxonasi.

# **1-AMALIY VAZIFA**

## N-o'lchamli massivlar yaratish

In [ ]:
# Numpy kutubxonasini chaqirib olish
import numpy as np

### Masala(1): 1-o'lchamli massivlar yaratish

**Masala sharti :** Elementlari ixtiyoriy  *n* ta  (*n* > 0, butun son) bo'lgan 1-o'lchamli massiv (array) yaratuvchi funksiyani davom ettiring.

**Yordam :**  `array` yoki `random` funksiyasidan foydalaning.

**Funksiya yaratilishi haqida darslik:** [bog'lanma](https://www.youtube.com/watch?v=_aDyBPYAeyU&list=PLwsopmzfbOn9Lw5D7a26THpBDgAma1Sus&index=22)


In [3]:
import numpy as np

In [1]:
def one_dim(n):
  return np.random.randint(0,100, size=n)

In [4]:
# masalan 7 elementli massiv
print(one_dim(7))

[ 2 38 85 42  6  2 30]


In [5]:
#Yoki
def one_dim(n):
  return np.arange(n)
#masalan n=10 bo'lsin
print(one_dim(10))

[0 1 2 3 4 5 6 7 8 9]


### Yuqoridagi yozgan funksiyangizni tekshirish uchun, quyidagi cellni yuriting.

In [ ]:
#@title Tekshirish (natijada hech qanday xatolik yuz bermasligi kerak)
"""Check that function returns the correct output for several inputs"""
for i in range(1, 10):
  assert len(one_dim(i)) == i, f"n elementlar soni, funksiyada noto'g'ri qo'llanilgan" # n elementlar soni
  arr = one_dim(i) # massiv
  assert arr.ndim == 1, f"1-o'lchamli massiv aniqlanmadi"# massiv o'lchami
  assert type(arr) == np.ndarray, f"massiv aniqlanmadi" #numpy array

_____

### Masala(2) 2-o'lchamli massivlar yaratish

**Masala :** Shakli `shape(r, c)` bo'lgan 2-o'lchamli massiv (array) yaratuvchi funksiyani davom ettiring.  

**Yordam :** numpy kutubxonasida massivlar yaratuvchi funksiyalarining istalganidan foydlanishingiz mumkin.


In [6]:
import numpy as np
def two_dim(r,c):
  return np.random.randint(0,100, size=(r,c))



In [7]:
#masalan 3x4 o'lchamli massiv
print(two_dim(3,4))

[[13 64 30 76]
 [79 95 69 88]
 [87 73 18 44]]


In [8]:
#Yoki boshqa usuli
def two_dim(r,c):
  return np.arange(r*c).reshape(r,c)

In [12]:
#Msalan 3x4 o'lchamli massiv
print(two_dim(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Yuqoridagi yozgan funksiyangizni tekshirish uchun, quyidagi cellni yuriting.

In [ ]:
#@title Tekshirish (natijada hech qanday xatolik yuz bermasligi kerak)
"""Check that function returns the correct output for several inputs"""
arr = two_dim(3, 2) # massiv
assert arr.shape == (3, 2), f"funksiyada, o'lchamlar noto'g'ri qo'llanilgan" # shape
assert arr.ndim == 2, f"2-o'lchamli massiv aniqlanmadi" # massiv o'lchami
assert type(arr) == np.ndarray, f"massiv aniqlanmadi"# #numpy array